/*

By Abdullahi Farah

Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

public class Problem2 {
	public static void main(String[] args){
		Problem2 test = new Problem2();
		System.out.println(test.solve());
	}

	public String solve(){
		// For initial even terms
		int sum = 2;
		int initialValue = 2;
		int nextValue = 3;

		while(nextValue < 4000000){
			if (nextValue%2 == 0){
				sum += nextValue;
			}
			nextValue += initialValue;
			initialValue = nextValue - initialValue;
			
		}

		return Integer.toString(sum);
	}
}
















